apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
resources:
# Longhorn 1.8.1 is compatible with CSI Snapshot Controller 8.2.0
# (https://github.com/kubernetes-csi/external-snapshotter)
# In this version of CSI Snapshot Controller kustomization files are available
- https://github.com/kubernetes-csi/external-snapshotter/client/config/crd/?ref=v8.3.0
- https://github.com/kubernetes-csi/external-snapshotter/deploy/kubernetes/snapshot-controller/?ref=v8.3.0

# Reduce replicas for homelab (HA not needed)
patches:
- target:
    kind: Deployment
    name: snapshot-controller
  patch: |-
    - op: replace
      path: /spec/replicas
      value: 1