# flux-instance helm values (dev overlay)
instance:
  sync:
    kind: GitRepository
    url: https://github.com/JacobCGade/homelab
    ref: refs/heads/master
    path: kubernetes/cluster/dev
    interval: 1h