apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sure

resources:
  - ../../base

components:
  - ../../components/ingress

configMapGenerator:
  - name: sure-helm-values
    behavior: merge
    files:
      - overlay-values.yaml=values.yaml

patches:
  - target:
      group: helm.toolkit.fluxcd.io
      kind: HelmRelease
      name: sure
    path: helm-patch.yaml
