---

common_packages:
  - curl
  - bridge-utils
  # Longhorn requirements
  - open-iscsi
  - nfs-common
  - cryptsetup
  - dmsetup

rpi_packages:
  - libraspberrypi-bin
  # - linux-modules-extra-raspi  # Not available in Ubuntu 24.04
  - fake-hwclock
  - bridge-utils
