---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: vaultwarden-app
  namespace: flux-system
spec:
  interval: 30m
  targetNamespace: vaultwarden
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: longhorn-app
    - name: cert-manager-app
    - name: ingress-nginx-app
  path: ./kubernetes/apps/vaultwarden/app/overlays/prod
  prune: true
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-settings
