---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: promtail-app
  namespace: flux-system
spec:
  interval: 30m
  timeout: 15m
  targetNamespace: loki
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: loki-app
  path: ./kubernetes/platform/promtail/app/overlays/prod
  prune: true
  wait: true
