---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: tempo-app
  namespace: flux-system
spec:
  interval: 30m
  targetNamespace: tempo
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: external-secrets-config
    # Using external Minio on node1 instead of in-cluster minio-app
  path: ./kubernetes/platform/tempo/app/overlays/prod
  prune: true
  wait: true
