---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sure
spec:
  interval: 30m
  chart:
    spec:
      chart: ./charts/sure
      sourceRef:
        kind: GitRepository
        name: sure
        namespace: flux-system
  releaseName: sure
  targetNamespace: sure
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  valuesFrom:
    - kind: ConfigMap
      name: sure-helm-values
      valuesKey: base-values.yaml
