apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ns.yaml
  - postgres.yaml
  - redis.yaml
  - sure-externalsecret.yaml
  - helm.yaml

configMapGenerator:
  - name: sure-helm-values
    files:
      - base-values.yaml=values.yaml

configurations:
  - kustomizeconfig.yaml
