---

# Install python3 pip and virtualenv packages
install_python_packages: true

# Set certbot python virtual environment
certbot_venv: /letsencrypt

# Cloudflare API token (set in picluster.yml)
# cloudflare_api_token: "{{ vault.certmanager.cloudflare.api_token }}"

# Certbot email for Let's Encrypt
certbot_email: "{{ acme_issuer_email | default('admin@example.com') }}"

# dns propagation in seconds
propagation_seconds: 120
