---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  CLUSTER_DOMAIN: homelab.jacobgade.com
  S3_BACKUP_SERVER: s3.jacobgade.com
  EXTERNAL_DNS_SERVER: 10.0.0.11
  NGINX_LOAD_BALANCER_IP: 10.0.0.65
  FLUENTD_LOAD_BALANCER_IP: 10.0.0.66
  ISTIO_GATEWAY_LOAD_BALANCER_IP: 10.0.0.67
  PI_ADMIN_FIRSTNAME: Jacob
  PI_ADMIN_LASTNAME: Gade
  PI_ADMIN_EMAIL: jacobcgade@gmail.com