---
all:
  children:
    control:
      hosts:
        apollo:
          hostname: apollo
          ansible_host: localhost
          ansible_connection: local
    #external:
      #hosts:
        #s3:
          #hostname: s3
          #ansible_host: s3.jacobgade.com
    picluster:
      hosts:
        node1: # Note: not part of k8s cluster (external node)
          hostname: node1
          ansible_host: 10.0.0.11
          ip: 10.0.0.11
          mac: 2c:cf:67:f3:a8:d3
          ansible_ssh_common_args: '-o ProxyCommand="ssh -W %h:%p root@192.168.0.21"'
        node2:
          hostname: node2
          ansible_host: 10.0.0.12
          ip: 10.0.0.12
          mac: e4:5f:01:2d:fd:19 # To be updated when node2 is setup
          ansible_ssh_common_args: '-o ProxyCommand="ssh -W %h:%p root@192.168.0.21"'
    raspberrypi:
      hosts:
        node[1:2]:
    k3s_cluster:
      children:
        k3s_master:
          hosts:
            node2:
    dns:
      hosts:
        node1:
    vault:
      hosts:
        node1:
    haproxy:
      hosts:
        node1:
    san:
      hosts:
        node1:
    s3:
      hosts:
        node1:
